version: "3.9"

services:
  www:
    container_name: www-nginx
    image: nginx:1.21-alpine
    networks:
      - web-tier
      - app-tier
    ports:
      - 8180:80
    volumes:
      - ./admin-portal:/app
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links: ["app-laravel", "pgadmin"]
    depends_on: ["app-laravel", "pgadmin"]

  php-fpm-alpine:
    container_name: php-fpm-alpine-builder
    build:
      context: .
      dockerfile: ./docker/php-fpm-alpine/Dockerfile
    networks:
      - app-tier
    ports:
      - 9000:9000
    volumes:
      - ./admin-portal:/app
    restart: "no"
    profiles: ["test"]

  app-laravel:
    container_name: app-laravel
    image: php:fpm-alpine
    networks:
      - app-tier
    ports:
      - 9000:9000
    volumes:
      - ./admin-portal:/app
    working_dir: /app/public
    restart: unless-stopped
    depends_on: ["db"]

  php-composer:
    container_name: php-composer
    image: composer:2.1.14
    restart: "no"
    networks:
      - app-tier
    command: install
    volumes:
      - ./admin-portal:/app
    working_dir: /app
    profiles: ["build"]

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - web-tier
      - db-tier
    ports:
      - "8082:80"
    links: ["db"]
    depends_on: ["db"]

  db:
    container_name: pgsql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      - db-tier
    ports:
      - "5432:5432"

networks:
  web-tier:
    driver: bridge
  app-tier:
    driver: bridge
  db-tier:
    driver: bridge